### ISSUE TITLE
修改密码时不生效，感觉用户名没取到

### ISSUE THREAD

**Issue by flytigerboy** [zhaojh329/oui#113]
Environment: (put here arch, model, OpenWrt version)
OpenWrt 19.07
Description:
在管理权页面修改密码不生效，浏览器调试，看起来好像没取到用户名啊，参数错误了
```
Uncaught (in promise) {"req":{"jsonrpc":"2.0","id":88,"method":"call","params":["ff687ee017d7320631dca6d8f1331ede","oui","set_password",{"password":"000000"}]},"error":{"code":-32602,"message":"Invalid params"}}
```

**Comment by zhaojh329** [comment]
Fixed.
https://github.com/zhaojh329/oui/commit/5e561fe743f4ada621f24fff03dece84092951ee
