### ISSUE TITLE
getting a directory, not a web page

### ISSUE THREAD

**Issue by outbackdingo** [zhaojh329/oui#140]
installed oui  and i get a directory listing, not a web page
```
![image](https://user-images.githubusercontent.com/52370034/130043621-067c2b56-eba6-4670-9295-9e16bfada550.png)

**Comment by zhaojh329** [comment]
Please confirm whether there are other HTTP servers running in your device, occupying port 80.

**Comment by outbackdingo** [comment]
fixed, removed legacy uhttpd
