### ISSUE TITLE
HOW TO FIX OPENWRT 21.

### ISSUE THREAD

**Issue by baonks** [zhaojh329/oui#145]
CMake Error at /home/ocay/Desktop/PROJEK/openwrt/staging_dir/host/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Libuhttpd (missing: LIBUHTTPD_INCLUDE_DIR) (Required is at
  least version "3.13")
Call Stack (most recent call first):
  /home/ocay/Desktop/PROJEK/openwrt/staging_dir/host/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:577 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibuhttpd.cmake:27 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)

**Comment by zhaojh329** [comment]
Vue3 + Nginx + Lua is coming...
