### ISSUE TITLE
oui-httpd CPU占用暴涨

### ISSUE THREAD

**Issue by sensiki** [zhaojh329/oui#147]
在oui前端调用一个没有返回的ubus接口时，oui-httpd CPU占用会暴涨。

![QQ截图20210914180808](https://user-images.githubusercontent.com/4695650/133241743-153eeb2c-ef00-4f31-951e-0302949418d7.png)
![QQ截图20210914180945](https://user-images.githubusercontent.com/4695650/133241769-7a6205ad-f96d-4fe2-835f-b282b5d1cdc5.png)

**Comment by zhaojh329** [comment]
Vue3 + Nginx + Lua is coming...
