### ISSUE TITLE
 disable ipV6，oui not work 

### ISSUE THREAD

**Issue by bbear218** [zhaojh329/oui#176]
Environment: (put here arch, model, OpenWrt version)
openwrt19.09
Description:
Remove Enable IPv6 support in packages under Global build settings，  disable ipV6，oui not work 
Please help me, thanks.

**Comment by Paull** [comment]
maybe it's because oui-httpd can't start. log into ssh and try this.
```bash
uci del_list oui-httpd.main.listen_http='[::]:80'
uci del_list oui-httpd.main.listen_https='[::]:443'
uci commit oui-httpd
/etc/init.d/oui-httpd restart
```

**Comment by zhaojh329** [comment]
Vue3 + Nginx + Lua is coming...
