### ISSUE TITLE
Selecting oui-rpc-core package makes the entire compilation fail 

### ISSUE THREAD

**Issue by anujaya95** [zhaojh329/oui#190]
Environment:
Architecture: x86
OpenWrt Version: 21.02.3

Description:
If I try to compile an OpenWrt image with oui-rpc-core alone without any oui application or httpd package, it works but if I choose any of these aforementioned packages, the compilation fails. 

![Screenshot_20220829_095330](https://user-images.githubusercontent.com/97794663/187154873-a57de83c-ae3f-46c4-986a-b69e2b82bf2e.png)

**Comment by zhaojh329** [comment]
Oui-httpd is no longer available in the latest version.

```bash
rm -rf feeds
./scripts/feeds update -a
./scripts/feeds install -a
```

See https://zhaojh329.github.io/oui/ for more info.
