### ISSUE TITLE
这个需要花很长时间吗？一动不动，谢谢

### ISSUE THREAD

**Issue by lanhaner** [zhaojh329/oui#191]
Environment: (x86_64, CentOS-7, OpenWrt 22.03.01)

Description:

```
./scripts/feeds update -a
Updating feed 'packages' from 'https://git.openwrt.org/feed/packages.git' ...
Cloning into './feeds/packages'...

```

**Comment by zyw0605688** [comment]
> 

这个是网络问题
第一个办法：翻墙
第二个办法：
将需要使用的仓库https://git.openwrt.org/feed/packages.git，同步到gitee，然后编辑feeds配置文件，更改为你自己的gitee仓库地址

**Comment by lanhaner** [comment]
好的，谢谢
