### ISSUE TITLE
errors  when making

### ISSUE THREAD

**Issue by lanhaner** [zhaojh329/oui#195]
Environment: (x86_64, centOS7, OpenWrt 21.02)

Description:
[build.log](https://github.com/zhaojh329/oui/files/9493819/build.log)

大侠，再帮忙看看，详见build.log。谢谢

**Comment by zhaojh329** [comment]
```
Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
```
提示已经很明显了。

**Comment by lanhaner** [comment]
谢谢，这个日志才是遇到的问题~
[build.log](https://github.com/zhaojh329/oui/files/9494579/build.log)

**Comment by lanhaner** [comment]
我换个路径重新编译，谢谢
