### ISSUE TITLE
重新生成package-lock.json丢失css代码

### ISSUE THREAD

**Issue by zzzzzhy** [zhaojh329/oui#197]
我重新生成package-lock.json后,npm run build生成的js文件缺少了style的代码,请问这是什么原因引起的?
packag.json的内容我没有改动过

**Comment by zhaojh329** [comment]
为什么要重新生成 package-lock.json ？

**Comment by zzzzzhy** [comment]
找到问题了,vite版本的问题,"vite": "^3.0.4",这个没有固定在3.0.4,install之后会变成最新的3.1.2
目前vite3.1.0以上版本会有css丢失的问题https://github.com/vitejs/vite/issues/10137
把"vite": "^3.0.4"改成"vite": "3.0.4"固定版本就没问题了
