### ISSUE TITLE
Add screenshots or an online demo

### ISSUE THREAD

**Issue by aparcar** [zhaojh329/oui#20]
It's a nice interface, would be interesting to give potential users an impression before they compile it on their own.
![Screenshot_2019-07-04 OpenWrt - oui(5)](https://user-images.githubusercontent.com/16000931/60661186-bf48ad80-9e59-11e9-946a-f238c19c24f9.png)
![Screenshot_2019-07-04 OpenWrt - oui(4)](https://user-images.githubusercontent.com/16000931/60661188-bf48ad80-9e59-11e9-8520-cefcd043c9f3.png)
![Screenshot_2019-07-04 OpenWrt - oui(3)](https://user-images.githubusercontent.com/16000931/60661189-bfe14400-9e59-11e9-86f0-f7c90360d349.png)
![Screenshot_2019-07-04 OpenWrt - oui(2)](https://user-images.githubusercontent.com/16000931/60661190-bfe14400-9e59-11e9-8354-72412780d219.png)
![Screenshot_2019-07-04 OpenWrt - oui(1)](https://user-images.githubusercontent.com/16000931/60661191-c079da80-9e59-11e9-96c3-8338df36b725.png)
![Screenshot_2019-07-04 OpenWrt - oui](https://user-images.githubusercontent.com/16000931/60661192-c079da80-9e59-11e9-9d54-f274d1618f65.png)

**Comment by zhaojh329** [comment]
Thanks.

**Comment by zhaojh329** [comment]
![fileinput](https://user-images.githubusercontent.com/28673295/64079407-ba00c580-cd19-11e9-8990-3346fc58a987.gif)
