### ISSUE TITLE
oui-rpc not found

### ISSUE THREAD

**Issue by gholamrezaeipt** [zhaojh329/oui#207]
Environment: v22.0.3

Description:

1. Download openwrt from git (git clone)
2. install packages and feeds
3. install oui (add to feed config and install)
4. in oui-ui-core/htdoc directory run `npm install` & `npm run dev`
5. open given link in browser
6. in browser developer tools > networks i saw a 404 error: `localhost:port/oui-rpc` not found

in vite.config.json

```
server: {
      proxy: {
        '/oui-rpc': {
          target: 'http://192.168.1.151',
          secure: false
        },
        '/oui-upload': {
          target: 'http://192.168.1.151',
          secure: false
        },
        '/oui-download': {
          target: 'http://192.168.1.151',
          secure: false
        }
      }
    }
```

and 192.168.1.151 is Openwrt that installed on VMWare
![image](https://user-images.githubusercontent.com/90236081/206831593-8e228fcc-68e2-4aec-bdf6-9e4bd6000464.png)

**Question: Which part is wrong for development?**

**Comment by zhaojh329** [comment]
You need to install oui to your device first, then you can debug it.

**Comment by zhaojh329** [comment]
Don't select uhttpd.

**Comment by gholamrezaeipt** [comment]
> Don't select uhttpd.

How can i do not select uhttpd? which file exactly?

**Comment by castillofrancodamian** [comment]
> > Don't select uhttpd.
> 
> How can i do not select uhttpd? which file exactly?

In the make menuconfig you can select which packages to install and uninstall.
