### ISSUE TITLE
ADD MENU INTERFACE,ETC...

### ISSUE THREAD

**Issue by kebonzero** [zhaojh329/oui#208]
How to add menu network, interface,wireless etc...
Please add for example...

Thanks...🙏

Please answer...

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/oui/tree/master/applications

**Comment by kebonzero** [comment]
> https://github.com/zhaojh329/oui/tree/master/applications
I'm still new, I don't really understand....😇😇
