### ISSUE TITLE
怎么样可以获取和修改系统时间，能用lua-eco里的time.now()吗

### ISSUE THREAD

**Issue by yunhai20082008** [zhaojh329/oui#223]
如题

**Comment by zhaojh329** [comment]
获取可以，但修改，你需要另外实现。要么写 C 绑定 Lua，要么通过 Lua 执行 shell 脚本

**Comment by yunhai20082008** [comment]
> 获取可以，但修改，你需要另外实现。要么写 Lua 绑定 C，要么通过 Lua 执行 shell 脚本

能给指导下吗，或者给指点下哪个文件里有类似的调用过程，我是个新手，折腾一天了也没搞定

**Comment by yunhai20082008** [comment]
我在vscode得oui-rpc-core得system.lua和op系统内得同文件同位置加了下面代码：
`function M.set_localtime(params)
    local time = 1000000000
    time.at(0.5, function()
        os.execute('date -s' .. time)
    end)
end
`
浏览器得按钮触发加了下面代码：
`    syncTime() {
      this.$oui.call('date', '-s', '1000000000')
      //this.$oui.call('system', 'set_localtime', '1000000000')
    },`
第二段代码中得两个命令好像都没有执行成功，是哪里做的有问题吗

**Comment by zhaojh329** [comment]
> 

```
function M.set_localtime(c)
    local time = params.time
    os.execute('date -s ' .. time)
end
```

```
  syncTime() {
    const time = '2019-05-29 10:58:00'
    this.$oui.call('system', 'set_localtime', { time })
  }
```

**Comment by yunhai20082008** [comment]
> 

不行哦

**Comment by zhaojh329** [comment]
```
function M.set_localtime(params)
    local time = params.time
    os.execute('date -s ' .. time)
end
```

**Comment by yunhai20082008** [comment]
> ```
> function M.set_localtime(params)
>     local time = params.time
>     os.execute('date -s ' .. time)
> end
> ```

这个也试了，还试了
```
  syncTime() {
    //const time = '2019-05-29 10:58:00'
    this.$oui.call('system', 'set_localtime', {
       time: '2019-05-29 10:58:00'
    })
  }
```

**Comment by zhaojh329** [comment]
需要配置权限

**Comment by yunhai20082008** [comment]
虽然找到了解决办法。也觉得这个项目挺好用，但是想想，vue的版权人是一个人，你这项目版权人也是一个人，我还是不贡献代码了，也不用这个项目了，我还是去用bootstrap了。
