### ISSUE TITLE
too many inode was used when build oui

### ISSUE THREAD

**Issue by poweel** [zhaojh329/oui#240]
for i in ./*; do echo $i; find $i | wc -l; done

./oui-app-acl-git-2023.224.10990-ce9ea17
174265
./oui-app-backup-git-2023.224.10990-ce9ea17
174265
./oui-app-demo-git-2023.224.10990-ce9ea17
174269
./oui-app-dhcp-lease-git-2023.224.10990-ce9ea17
174265
./oui-app-home-git-2023.224.10990-ce9ea17
174256
./oui-app-layout-git-2023.224.10990-ce9ea17
174258
./oui-app-login-git-2023.224.10990-ce9ea17
174255
./oui-app-stations-git-2023.224.10990-ce9ea17
174269
./oui-app-system-git-2023.224.10990-ce9ea17
174266
./oui-app-upgrade-git-2023.224.10990-ce9ea17
174265

**Comment by zhaojh329** [comment]
#272
