### ISSUE TITLE
输入用户名密码后按回车不能登录

### ISSUE THREAD

**Issue by poweel** [zhaojh329/oui#241]
Environment: (put here arch, model, OpenWrt version)

输入用户名密码后按回车不能登录，需要按tab再按回车，或者用鼠标点击登录才行

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/oui/commit/67c8da1451bef063681114cf3598f04c0e271cb8

**Comment by zhaojh329** [comment]
已支持。
