### ISSUE TITLE
Warning  Regard as Error

### ISSUE THREAD

**Issue by gao114882** [zhaojh329/oui#25]
Environment: (put here arch, model, OpenWrt version)

Description:

build_dir/target-arm-linux-gnueabi_glibc/oui-io-util/main.c:151:3: error: ignoring return value of 'read', declared with attribute warn_unused_result [-Werror=unused-result]
   read(fds[0], chksum, 32);
build_dir/target-arm-linux-gnueabi_glibc/oui-io-util/main.c:612:3: error: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Werror=unused-result]
   chdir("/");
   ^~~~~~~~~~

**this params should have return params** our  makefile  regard this is error.

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by zhaojh329** [comment]
Fixed. 28e2631
