### ISSUE TITLE
the page services return with code 404.

### ISSUE THREAD

**Issue by sbilly** [zhaojh329/oui#29]
Environment: (put here arch, model, OpenWrt version)
x64
OpenWrt 18.06 
vmware

Description:
`/#/home` works fine.
![image](https://user-images.githubusercontent.com/123563/64779944-d8748580-d591-11e9-866a-7fa213cc6bd8.png)

`/#/services` return http error code 404.

![image](https://user-images.githubusercontent.com/123563/64779894-afec8b80-d591-11e9-9edf-815bf09e8be9.png)

**Comment by zhaojh329** [comment]
Fixed. #5c5a3fe
