### ISSUE TITLE
Node.js version compare error and workaround

### ISSUE THREAD

**Issue by Pengchengistaken** [zhaojh329/oui#302]
Environment: (put here arch, model, OpenWrt version)
Ubuntu 24.04 LTS
Node.js version: 20.16.0

Description:

```
Checking Node.js for building oui...
Using Node.js from Host
Node.js path: /home/lipc/.nvm/versions/node/v20.16.0/bin/node
Node.js version: 20.16.0
Node.js 20.9+ is required
```

tempertory workaround:
Make sure your Node.js version is 20.9+, then
modify #line 40 of node.mk to 
```
$(call ColorError, "Node.js $(1)+ is required");true; \
```

root cause and fix:
let's wait for the fix..

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/oui/commit/6c7aefacba37e82669a1e484f8fc6588f448ff92
