### ISSUE TITLE
更新 oui-app-* 代码不生效

### ISSUE THREAD

**Issue by sbilly** [zhaojh329/oui#33]
Environment: (put here arch, model, OpenWrt version)
18.06
x64

Description:
更新固件中的 oui-app-* 代码，在浏览器中发现更新的代码不生效。在隐身模式下访问，发现相关代码已经更新。

**Comment by Magical-Lin** [comment]
这个是浏览器的锅。清空一下访问记录或cookie

**Comment by sbilly** [comment]
我感觉是 header 设置不对，导致基于文件后缀名的缺省浏览器缓存机制导致的

**Comment by sbilly** [comment]
这个问题应该是 Header 设置不对导致的。
