### ISSUE TITLE
ubus.call('oui.ui', 'lang') "Object not found"

### ISSUE THREAD

**Issue by yaoyuanyylyy** [zhaojh329/oui#38]
你好，我在openwrt路由器上部署后，有时候访问web时没有东西，在console下看到了下面的错误提示，指向了router.js文件63行。只有重启路由器之后才能正常访问，请问一下要怎么解决？

Uncaught (in promise) 
{req: Array(3), error: {…}}
error:{code: -32000, message: "Object not found"}
req:(3) ["oui.ui", "lang", {…}]
__proto__:Object

**Comment by zhaojh329** [comment]
可能路由器上的oui程序退出了。手动运行oui，看下报什么错误。/usr/sbin/oui
