### ISSUE TITLE
PROXY ERROR /ubus

### ISSUE THREAD

**Issue by m-bbn** [zhaojh329/oui#41]
Environment: (put here arch, model, OpenWrt version)

Description:
We cloned the master branch of OUI framework and run the project but we get this error 
**"Proxy error : Could not proxy request /ubus from localhost:8080 to http://107.105.159.22 (ECONNREFUSED)."** 

We don't know if we need to set up a server or OpenWrt to run the project in our local.

Hope someone can give us an input. Thanks

![image](https://user-images.githubusercontent.com/58934294/70901845-8468b980-2036-11ea-91df-912a49027409.png)

**Comment by zhaojh329** [comment]
https://zhaojh329.github.io/oui/guide/

**Comment by m-bbn** [comment]
> https://zhaojh329.github.io/oui/guide/

Hi @zhaojh329 , thank you for your response but we already follow that steps https://zhaojh329.github.io/oui/guide/getting-started.html#debugging-front-end-code

**Comment by lqfcu3mtd** [comment]
I had the same problem，follow that steps has the same error. 
![image](https://user-images.githubusercontent.com/49577998/71052841-927a1f80-2187-11ea-9bba-c6ae053004e4.png)
![image](https://user-images.githubusercontent.com/49577998/71052889-b3427500-2187-11ea-85f1-1ecb85e7dfc6.png)
![image](https://user-images.githubusercontent.com/49577998/71052905-c2292780-2187-11ea-812b-f1cca1cca4af.png)

module.exports = {
  indexPath: 'oui.html',
  productionSourceMap: false,
  devServer: {
    proxy: {
      '/ubus': {
        target: '192.168.1.1'
      },
      '/cgi-bin/': {
        target: '192.168.1.1'
      },
      '/views/': {
        target: '192.168.1.1'
      },
      '/i18n/': {
        target: '192.168.1.1'
      }
    }
  },
  pluginOptions: {
    i18n: {
      locale: 'en',
      fallbackLocale: 'en',
      localeDir: 'locales',
      enableInSFC: false
    }
  }
}

**Comment by lqfcu3mtd** [comment]
In vue.config.js  the 'target' must contain 'http: //'   
`devServer: {
    proxy: {
      '/ubus': {
        target: 'http://192.168.1.1'
      },
      '/cgi-bin/': {
        target: 'http://192.168.1.1'
      },
      '/views/': {
        target: 'http://192.168.1.1'
      },
      '/i18n/': {
        target: 'http://192.168.1.1'
      }
    }
  }`
