### ISSUE TITLE
编译出的应用有2M，能否降低

### ISSUE THREAD

**Issue by poweel** [zhaojh329/oui#44]
Environment: (put here arch, model, OpenWrt version)

Description:
我编译处理的js脚本和样式文件一共有2M，这个是正常的，还是我的编译有问题？
```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by zhaojh329** [comment]
依赖的element-ui，这个库比较大。

**Comment by poweel** [comment]
element-ui这个库现在是按需加载的，还是全部加载了？

**Comment by zhaojh329** [comment]
按需
