### ISSUE TITLE
Blank page after few weeks

### ISSUE THREAD

**Issue by Manssizz** [zhaojh329/oui#53]
Environment:  mipsel_24kc, Asus RT-AC51U, Openwrt 19

Description:
i have trouble with OUI after using OUI few weeks, when i access my router, OUI just blank page. but work with LuCI

proof:
https://gofile.io/?c=d9LLWu

**Comment by laoshaw** [comment]
same issue here, something is broken,  a blank homepage is all I got with development branch

**Comment by laoshaw** [comment]
![Screenshot from 2020-05-02 23-39-09](https://user-images.githubusercontent.com/18351761/80898858-465ef000-8cce-11ea-8322-7ed60ecd1503.png)

**Comment by baidxi** [comment]
清除浏览器缓存
