### ISSUE TITLE
[Build] 'package/feeds/vuci/vuci-ui-base/compile' failed

### ISSUE THREAD

**Issue by arky** [zhaojh329/oui#6]
Unable to complete build. There seems some issue with build/compile stage. 

Full Error: http://paste.ubuntu.com/p/8WPzWyrsJ5/
`-openwrt-linux-muslgnueabi-ld NM="arm-openwrt-linux-muslgnueabi-gcc-nm" CC="arm-openwrt-linux-muslgnueabi-gcc" GCC="arm-openwrt-linux-muslgnueabi-gcc" CXX="arm-openwrt-linux-muslgnueabi-g++" RANLIB="arm-openwrt-linux-muslgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-muslgnueabi-strip OBJCOPY=arm-openwrt-linux-muslgnueabi-objcopy OBJDUMP=arm-openwrt-linux-muslgnueabi-objdump SIZE=arm-openwrt-linux-muslgnueabi-size CROSS="arm-openwrt-linux-muslgnueabi-" ARCH="arm" ; make[4]: Entering directory '/home/arky/Code/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/vuci-ui-base' make[4]: *** No targets specified and no makefile found.  Stop. make[4]: Leaving directory '/home/arky/Code/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/vuci-ui-base' Makefile:54: recipe for target '/home/arky/Code/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/vuci-ui-base/.built' failed make[3]: *** [/home/arky/Code/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/vuci-ui-base/.built] Error 2 make[3]: Leaving directory '/home/arky/Code/openwrt/feeds/vuci/vuci-ui-base' Command exited with non-zero status 2 time: package/feeds/vuci/vuci-ui-base/compile#0.22#0.11#0.55 package/Makefile:107: recipe for target 'package/feeds/vuci/vuci-ui-base/compile' failed make[2]: *** [package/feeds/vuci/vuci-ui-base/compile] Error 2 make[2]: Leaving directory '/home/arky/Code/openwrt' package/Makefile:103: recipe for target '/home/arky/Code/openwrt/staging_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/stamp/.package_compile' failed make[1]: *** [/home/arky/Code/openwrt/staging_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/arky/Code/openwrt' /home/arky/Code/openwrt/include/toplevel.mk:216: recipe for target 'world' failed make: *** [world] Error 2
`--

`

**Comment by zhaojh329** [comment]
Fixed.

**Comment by zhaojh329** [comment]
Fixed.
