### ISSUE TITLE
Add Oui to Openwrt General Packages Feed

### ISSUE THREAD

**Issue by arky** [zhaojh329/oui#69]
Please add Oui for inclusion in Openwrt/packages (https://github.com/openwrt/packages). This enables ease of deployment to wider openwrt devices. 

Here is an example of package inclusion commit. 
https://github.com/openwrt/packages/commit/0871991d8d732fc79c04259ec80da0f4a3d14fc6#diff-90530134f0e9c6482a9ceb7ba0bbed2a

**Comment by tiagogaspar8** [comment]
I'd love this too, It's an amazing interface, very well designed.
I can help if needed

**Comment by mgscreativa** [comment]
It would be great to have it as a general package!

**Comment by zhaojh329** [comment]
It seems that it needs to be split into a single package to merge into openwrt / packages.

**Comment by tiagogaspar8** [comment]
Can we do that?

**Comment by zhaojh329** [comment]
The best way to join OpenWrt is as feeds, like Luci.

**Comment by tiagogaspar8** [comment]
But will the OpenWRT team allow another feed? I believe they only accept the merge of packages into the existing feeds.
I didn't take a look but is it that complicated to separate oui into several packages and get them merged?

**Comment by tiagogaspar8** [comment]
@zhaojh329 have you ever tried to merge this as a feed? Have you ever seen anyone do that? I have been reading the packages and makefiles anda I believe that they don't fit any of the folders, aside from uhttpd, wich they could argue that would only be another version, I believe this requires another folder just like LuCi, since this is a "replacement".

Also, is there any way to make it run on nginx?

**Comment by zhaojh329** [comment]
> @zhaojh329 have you ever tried to merge this as a feed? Have you ever seen anyone do that? I have been reading the packages and makefiles anda I believe that they don't fit any of the folders, aside from uhttpd, wich they could argue that would only be another version, I believe this requires another folder just like LuCi, since this is a "replacement".
> 
> Also, is there any way to make it run on nginx?

No plan to support nginx.

**Comment by tiagogaspar8** [comment]
And have you ever tried to merge your feed to OpenWRT?
