### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by TautvydasD** [zhaojh329/oui#76]
Environment: (put here arch, model, OpenWrt version)
OpenWrt 18.06.8

Description: After uploading packages to system and running oui on browser.

```
chunk-vendors.84231e0e.js:1 Uncaught SyntaxError: Invalid or unexpected token
app.1eac7929.js:1 Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by TautvydasD** [comment]
On OpenWrt master running only oui. ``` http://localhost``` shows only content of folder ``` /www ```

**Comment by zhaojh329** [comment]
Try chrome.

**Comment by TautvydasD** [comment]
On Chrome

![image](https://user-images.githubusercontent.com/37388918/95581470-c50c4600-0a41-11eb-9da3-c96b98f25fd9.png)

**Comment by zhaojh329** [comment]
Please stop other http server, such as uhttpd. And then restart oui-httpd.

**Comment by TautvydasD** [comment]
Thx. :)
