### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by m-alperensener** [zhaojh329/oui#80]
Environment: (openwrt, linkit7688, OpenWrt 19.7)

Description:
Hi
I followed exactly whats written in 'How to build?' However no success. I am getting *** No rule to make target 'package/feeds/oui/oui-ui/compile.

I have checked all package components with menuconfig. When I check the package/feeds/oui directory I only see application sub directories and individual mk files, however no oui-ui folder or mkfile.

Update:
I have manually copied oui.mk and oui-app.mk to package/feeds/oui directory
Now I got the error while compiling: Could NOT find Libev (missing: LIBEV_LIBRARY LIBEV_INCLUDE_DIR)

I specially selected libev to be compiled

Update:
I deselected oui using menuconfig recompiled, then added oui and compiled now I got the error;
Could NOT find Libuhttpd: Found unsuitable version "2.2", but required is
  at least "3.4"

Update:
I fetch the latest openwrt git. Compiled the oui succesfully. when I try reach web ui, the first screen is the base directory.
I think "How to" section must be more deteiled

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/oui/issues/73
