### ISSUE TITLE
build error due to missing urldecode from download.c

### ISSUE THREAD

**Issue by laoshaw** [zhaojh329/oui#93]
master branch openwrt, failed to build oui as urldecode is not defined in the repo.

Description:

```
download.c:77:5: error: implicit declaration of function 'urldecode' [-Werror=implicit-function-declaration]
     urldecode(params->path, sizeof(params->path), params->path, strlen(params->path));
```

**Comment by mengqingmeng** [comment]
> master branch openwrt, failed to build oui as urldecode is not defined in the repo.
> 
> Description:
> 
> ```
> download.c:77:5: error: implicit declaration of function 'urldecode' [-Werror=implicit-function-declaration]
>      urldecode(params->path, sizeof(params->path), params->path, strlen(params->path));
> ```

I had this problem too,how to solve this?

**Comment by zhaojh329** [comment]
https://github.com/openwrt/packages/pull/14789
